let tileConfig = {
    A: { "val": 1, "count": 9 },
    B: { "val": 3, "count": 2 },
    C: { "val": 3, "count": 2 },
    D: { "val": 2, "count": 4 },
    E: { "val": 1, "count": 12 },
    F: { "val": 4, "count": 2 },
    G: { "val": 2, "count": 3 },
    H: { "val": 4, "count": 2 },
    I: { "val": 1, "count": 9 },
    J: { "val": 8, "count": 1 },
    K: { "val": 5, "count": 1 },
    L: { "val": 1, "count": 4 },
    M: { "val": 3, "count": 2 },
    N: { "val": 1, "count": 6 },
    O: { "val": 1, "count": 8 },
    P: { "val": 3, "count": 2 },
    Q: { "val": 10, "count": 1 },
    R: { "val": 1, "count": 6 },
    S: { "val": 1, "count": 4 },
    T: { "val": 1, "count": 6 },
    U: { "val": 1, "count": 4 },
    V: { "val": 4, "count": 2 },
    W: { "val": 4, "count": 2 },
    X: { "val": 8, "count": 1 },
    Y: { "val": 4, "count": 2 },
    Z: { "val": 10, "count": 1 },
    Blank: { "val": 0, "count": 2 }
};

